// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameModes() {
  return window['go']['main']['App']['GetGameModes']();
}

export function QueryBattleData(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryBattleData'](arg1, arg2, arg3);
}
