// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameModes():Promise<Array<Record<string, any>>>;

export function QueryBattleData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
