// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBattleData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBattleData'](arg1, arg2, arg3);
}

export function GetCategoryOptions() {
  return window['go']['main']['App']['GetCategoryOptions']();
}

export function GetGameModes() {
  return window['go']['main']['App']['GetGameModes']();
}

export function GetHeroInfo(arg1) {
  return window['go']['main']['App']['GetHeroInfo'](arg1);
}

export function GetSavedPlayers() {
  return window['go']['main']['App']['GetSavedPlayers']();
}

export function QueryBattleData(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryBattleData'](arg1, arg2, arg3);
}

export function RemoveSavedPlayer(arg1) {
  return window['go']['main']['App']['RemoveSavedPlayer'](arg1);
}

export function SavePlayerID(arg1, arg2) {
  return window['go']['main']['App']['SavePlayerID'](arg1, arg2);
}
