// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBattleData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetCategoryOptions():Promise<Array<Record<string, any>>>;

export function GetGameModes():Promise<Array<Record<string, any>>>;

export function GetHeroInfo(arg1:number):Promise<Record<string, any>>;

export function GetSavedPlayers():Promise<Array<main.SavedPlayer>>;

export function QueryBattleData(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function RemoveSavedPlayer(arg1:string):Promise<boolean>;

export function SavePlayerID(arg1:string,arg2:string):Promise<boolean>;
