// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryBattleData(arg1:string,arg2:string):Promise<Record<string, any>>;
